name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  validate:
    name: Hassfest validation
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11d5960a326750d5838078e36cf38b85af677262" # v4
      - uses: home-assistant/actions/hassfest@e3fb68ebda13d88a0d695082f471ba2c83d025fb # master as of 2026-07-27
